server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/traffic_police
    username: jankbyte
    password: jankbyte
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          charset_name: UTF-8
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
